### PR TITLE
Discord.js v14 + more

### PR DESCRIPTION
**Pull request by WillFJS**
# Ready for review!
Closes: #269

### CODE REVIEW

**Comment by WillFJS** [comment]
@MidSpike The last few issues, I'm not too sure on how to solve

**Comment by WillFJS** [comment]
image

**Review by MidSpike — CHANGES_REQUESTED** [review]
@WillFJS all of the event files should export a name defined by Discord.js
image
(like the above)

**Review by MidSpike — APPROVED** [review]

**Review by rossloika — APPROVED** [review]
Didn't notice any issues/errors. Just in need of a test to ensure it works. 👍

**Comment by MidSpike** [comment]
# Tested, appears to work properly after most recent commit

**Review by rossloika — CHANGES_REQUESTED** [review]
Getting messages from staff members, they are unable to respond to tickets once the user clicked "I am done filling out instructions"

I believe the issue consists of the bot not being able to add the role to the channel of the ticket and give access to the support role dedicated to the support category.

**Comment by WillFJS** [comment]
> Getting messages from staff members, they are unable to respond to tickets once the user clicked "I am done filling out instructions"
> 
> I believe the issue consists of the bot not being able to add the role to the channel of the ticket and give access to the support role dedicated to the support category.

This issue has been fixed

**Review by MidSpike — CHANGES_REQUESTED** [review]
It appears that some dependencies were updated outside of the scope of this specific pull request.
The copyright information has been altered.
Some commands have been altered without relation to this pull request.

**Pull request closed without merging**
